# Generated by Django 5.2.9 on 2025-12-28 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserScope',
        ),
    ]
