# Generated by Django 5.2.9 on 2025-12-29 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_domainevent_approval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approval',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='approval',
            name='requested_by',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='actor',
        ),
        migrations.DeleteModel(
            name='DomainEvent',
        ),
        migrations.AlterUniqueTogether(
            name='userscope',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userscope',
            name='plant',
        ),
        migrations.RemoveField(
            model_name='userscope',
            name='user',
        ),
        migrations.DeleteModel(
            name='Approval',
        ),
        migrations.DeleteModel(
            name='AuditLog',
        ),
        migrations.DeleteModel(
            name='UserScope',
        ),
    ]
