# Generated by Django 5.2.9 on 2026-02-07 09:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0008_remove_employeeprofile_bitable_record_id'),
        ('org', '0008_delete_departmentsection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EHSItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=255)),
                ('item_type', models.CharField(choices=[('BOOLEAN', 'Yes / No'), ('TEXT', 'Text'), ('NUMBER', 'Number'), ('PHOTO', 'Photo'), ('DROPDOWN', 'Dropdown'), ('DATE', 'Date'), ('RISK_MATRIX', 'Risk Matrix')], max_length=30)),
                ('required', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='EHSFormTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ehs_form_templates', to='org.department')),
                ('plants', models.ManyToManyField(blank=True, to='org.plant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EHSFormVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_number', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='ehs_engine.ehsformtemplate')),
            ],
            options={
                'ordering': ['-version_number'],
                'unique_together': {('template', 'version_number')},
            },
        ),
        migrations.CreateModel(
            name='EHSItemOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='ehs_engine.ehsitem')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='EHSRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('PHOTO_REQUIRED', 'Photo Required'), ('REMARK_REQUIRED', 'Remark Required'), ('ESCALATE', 'Escalate')], max_length=50)),
                ('condition_value', models.CharField(max_length=50)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='ehs_engine.ehsitem')),
            ],
        ),
        migrations.CreateModel(
            name='EHSSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField()),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='ehs_engine.ehsformversion')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='ehsitem',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ehs_engine.ehssection'),
        ),
        migrations.CreateModel(
            name='EHSSubmission',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CLOSED', 'Closed')], default='DRAFT', max_length=50)),
                ('risk_score', models.PositiveIntegerField(default=0)),
                ('risk_category', models.CharField(blank=True, max_length=20)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='org.plant')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ehs_engine.ehsformversion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CAPA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('corrective_action', models.TextField()),
                ('preventive_action', models.TextField(blank=True)),
                ('target_date', models.DateField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('VERIFIED', 'Verified')], default='OPEN', max_length=20)),
                ('responsible_person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capas', to='ehs_engine.ehssubmission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EHSWorkflowTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ehs_engine.ehsformtemplate')),
            ],
        ),
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likelihood', models.PositiveSmallIntegerField()),
                ('severity', models.PositiveSmallIntegerField()),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk_assessment', to='ehs_engine.ehssubmission')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=100)),
                ('comment', models.TextField(blank=True)),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_logs', to='ehs_engine.ehssubmission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('role_required', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identity.role')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='ehs_engine.ehsworkflowtemplate')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='ehsitem',
            unique_together={('section', 'item_id')},
        ),
        migrations.CreateModel(
            name='EHSResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No'), ('NA', 'Not Applicable')], max_length=3, null=True)),
                ('text_value', models.TextField(blank=True)),
                ('number_value', models.FloatField(blank=True, null=True)),
                ('date_value', models.DateField(blank=True, null=True)),
                ('remark', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='ehs_evidence/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ehs_engine.ehsitem')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='ehs_engine.ehssubmission')),
            ],
            options={
                'unique_together': {('submission', 'item')},
            },
        ),
    ]
