# Generated by Django 5.2.9 on 2026-02-07 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehs_engine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ehsresponse',
            name='date_value',
        ),
        migrations.RemoveField(
            model_name='ehsresponse',
            name='number_value',
        ),
        migrations.RemoveField(
            model_name='ehsresponse',
            name='text_value',
        ),
        migrations.AddField(
            model_name='ehsformtemplate',
            name='bitable_app_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ehsformtemplate',
            name='bitable_table_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ehsitem',
            name='escalate_on_no',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ehsitem',
            name='require_photo_on_no',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ehsitem',
            name='require_remark_on_no',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ehsitem',
            name='severity_weight',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
