# Generated by Django 5.2.9 on 2026-02-07 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehs_engine', '0002_remove_ehsresponse_date_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ehsformtemplate',
            name='allow_multiple_submissions_per_day',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ehsformtemplate',
            name='recurrence',
            field=models.CharField(blank=True, choices=[('PER_SHIFT', 'Per Shift'), ('DAILY', 'Once Per Day'), ('WEEKLY', 'Weekly')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ehsformtemplate',
            name='require_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ehsformtemplate',
            name='require_incident_reference',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ehsformtemplate',
            name='template_type',
            field=models.CharField(choices=[('DAILY', 'Daily Audit'), ('SPECIAL', 'Special Audit')], default='DAILY', max_length=20),
        ),
        migrations.AddField(
            model_name='ehssubmission',
            name='incident_reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
