# Generated by Django 5.2.9 on 2026-02-07 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehs_engine', '0003_ehsformtemplate_allow_multiple_submissions_per_day_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ehsformtemplate',
            name='recurrence',
        ),
        migrations.AddField(
            model_name='ehsformtemplate',
            name='allowed_submissions',
            field=models.PositiveIntegerField(default=1, help_text='Number of submissions allowed per recurrence period'),
        ),
        migrations.AddField(
            model_name='ehsformtemplate',
            name='recurrence_scope',
            field=models.CharField(blank=True, choices=[('PER_SHIFT', 'Per Shift'), ('PER_DAY', 'Per Day'), ('PER_WEEK', 'Per Week')], max_length=20, null=True),
        ),
    ]
