# Generated by Django 5.2.9 on 2026-02-09 19:57

import ehs_engine.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehs_engine', '0004_remove_ehsformtemplate_recurrence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ehsresponse',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=ehs_engine.models.evidence_upload_path),
        ),
    ]
