"""
Central contract for dynamic forms.
ALL builders, validators, and renderers rely on this.
"""

# =========================
# ALLOWED FIELD TYPES
# =========================
FIELD_TYPES = (
    "text",
    "number",
    "dropdown",
    "multiselect",
    "boolean",
    "image",        # reference image OR evidence upload
    "date",
)

# =========================
# ALLOWED VALIDATIONS
# =========================
VALIDATIONS = (
    "required",
    "min",
    "max",
)

# =========================
# ALLOWED DEPENDENCIES
# =========================
DEPENDENCY_OPERATORS = (
    "equals",   # plant == "Plant A"
)

# =========================
# BUILDER FIELD CONTRACT
# (generated by UI only)
# =========================
FIELD_CONTRACT = {
    "key": str,                 # unique field key
    "label": str,               # UI label
    "type": FIELD_TYPES,        # one of FIELD_TYPES

    # Source mapping
    "source_column": str,       # column in source bitable
    "distinct": bool,           # for dropdowns

    # Validation
    "required": bool,
    "min_column": str,          # numeric only
    "max_column": str,          # numeric only

    # Dependency
    "depends_on": str,          # key of parent field
    "dependency_column": str,   # column to filter on
}
