# Generated by Django 5.2.9 on 2026-02-12 21:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='domainevent',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='domainevent',
            name='event_id',
            field=models.CharField(blank=True, db_index=True, help_text='External event ID for idempotency', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='object_id',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='object_type',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='domainevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='domainevent',
            name='event_type',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='domainevent',
            name='object_id',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='domainevent',
            name='object_type',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['actor', 'created_at'], name='audit_audit_actor_i_ec0f72_idx'),
        ),
        migrations.AddIndex(
            model_name='domainevent',
            index=models.Index(fields=['event_type'], name='audit_domai_event_t_30bf49_idx'),
        ),
        migrations.AddIndex(
            model_name='domainevent',
            index=models.Index(fields=['created_at'], name='audit_domai_created_867cb9_idx'),
        ),
        migrations.AddIndex(
            model_name='domainevent',
            index=models.Index(fields=['object_type', 'object_id'], name='audit_domai_object__5d35ca_idx'),
        ),
    ]
