# Generated by Django 5.2.9 on 2026-01-06 05:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org', '0006_alter_line_options_alter_plant_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Internal role code (e.g. QC, SUPERVISOR)', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Display name (e.g. Quality Control)', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='org.department')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_scopes', to='org.plant')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_scopes', to='identity.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'plant')},
            },
        ),
    ]
