# Generated by Django 5.2.9 on 2026-01-06 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_employeeprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='employee_email',
            field=models.EmailField(blank=True, help_text='Optional official/company email', max_length=254, null=True),
        ),
    ]
