# Generated by Django 5.2.9 on 2026-01-06 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0003_employeeprofile_employee_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='employee_email',
        ),
    ]
