# Generated by Django 5.2.9 on 2026-01-08 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0004_remove_employeeprofile_employee_email'),
        ('org', '0007_departmentsection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userscope',
            options={'verbose_name': 'User Scope', 'verbose_name_plural': 'User Scopes'},
        ),
        migrations.AddField(
            model_name='userscope',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_scopes', to='org.departmentsection'),
        ),
        migrations.AlterField(
            model_name='userscope',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_scopes', to='org.department'),
        ),
    ]
