# Generated by Django 5.2.9 on 2026-01-08 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0005_alter_userscope_options_userscope_section_and_more'),
        ('org', '0007_departmentsection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userscope',
            options={},
        ),
        migrations.RemoveField(
            model_name='userscope',
            name='section',
        ),
        migrations.AlterField(
            model_name='userscope',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='org.department'),
        ),
    ]
