# Generated by Django 5.2.9 on 2026-01-29 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0006_alter_userscope_options_remove_userscope_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='bitable_record_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
