# Generated by Django 5.2.9 on 2026-01-29 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0007_employeeprofile_bitable_record_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='bitable_record_id',
        ),
    ]
