# Generated by Django 5.2.9 on 2026-02-12 21:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0008_remove_employeeprofile_bitable_record_id'),
        ('org', '0010_remove_department_org_departm_plant_i_64f986_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='role',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userscope',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='employee_id',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='code',
            field=models.CharField(db_index=True, help_text='Internal role code (e.g. QC, SUPERVISOR)', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='userscope',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Optional department restriction within plant', null=True, on_delete=django.db.models.deletion.PROTECT, to='org.department'),
        ),
        migrations.AddIndex(
            model_name='userscope',
            index=models.Index(fields=['user', 'plant'], name='identity_us_user_id_39c41a_idx'),
        ),
        migrations.AddIndex(
            model_name='userscope',
            index=models.Index(fields=['plant', 'role'], name='identity_us_plant_i_efcb33_idx'),
        ),
    ]
