# Generated by Django 5.2.9 on 2026-02-20 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0010_permission_rolepermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_profiles', to='identity.role'),
        ),
    ]
