# Generated by Django 5.2.9 on 2026-02-20 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0011_employeeprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='category',
            field=models.CharField(blank=True, choices=[('PD', 'Product Development'), ('PE', 'Process Engineering'), ('PQE', 'Process Quality Engineering')], db_index=True, max_length=10, null=True),
        ),
    ]
