# Generated by Django 5.2.9 on 2026-02-20 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0012_role_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Short unique code like PD, PE, PQE, SAFETY', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Human readable name', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_approver', models.BooleanField(default=True, help_text='Whether this category can be used in approval flows')),
                ('order', models.PositiveIntegerField(default=0, help_text='Global default order (lower = earlier)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'code'],
            },
        ),
        migrations.RemoveField(
            model_name='role',
            name='category',
        ),
        migrations.AddField(
            model_name='role',
            name='approval_categories',
            field=models.ManyToManyField(blank=True, help_text='Approval categories this role can approve', related_name='roles', to='identity.approvalcategory'),
        ),
    ]
