# Generated by Django 5.2.9 on 2026-09-05 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0015_admin_panel_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='plain_password',
            field=models.CharField(blank=True, default='', help_text='Last-set plain text password — visible to superusers only', max_length=128),
        ),
    ]
