# Generated by Django 5.2.9 on 2026-01-05 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '__first__'),
        ('org', '0003_product_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=255)),
                ('item_type', models.CharField(choices=[('BOOLEAN', 'Yes / No'), ('TEXT', 'Text'), ('NUMBER', 'Number'), ('PHOTO', 'Photo')], max_length=20)),
                ('required', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField()),
                ('severity_weight', models.PositiveSmallIntegerField(default=1, help_text='Severity contribution if this item is non-conforming')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('PHOTO_REQUIRED', 'Photo Required'), ('REMARK_REQUIRED', 'Remark Required')], max_length=50)),
                ('condition_value', models.CharField(help_text='Expected value (e.g. YES / NO)', max_length=50)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='forms_engine.checklistitem')),
            ],
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='forms_engine.checklistsection'),
        ),
        migrations.CreateModel(
            name='ChecklistTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('bitable_app_token', models.CharField(blank=True, help_text='Lark Bitable App Token', max_length=255, null=True)),
                ('bitable_table_id', models.CharField(blank=True, help_text='Lark Bitable Table ID', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plants', models.ManyToManyField(blank=True, help_text='Plants where this SOP is applicable', to='org.plant')),
                ('products', models.ManyToManyField(blank=True, help_text='If empty, SOP applies to all products', to='org.product')),
            ],
        ),
        migrations.CreateModel(
            name='ChecklistVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='forms_engine.checklisttemplate')),
            ],
            options={
                'unique_together': {('template', 'version')},
            },
        ),
        migrations.AddField(
            model_name='checklistsection',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='forms_engine.checklistversion'),
        ),
        migrations.AlterUniqueTogether(
            name='checklistitem',
            unique_together={('section', 'item_id')},
        ),
        migrations.CreateModel(
            name='TemplateRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='template_assignments', to='identity.role')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='forms_engine.checklisttemplate')),
            ],
            options={
                'unique_together': {('template', 'role')},
            },
        ),
    ]
