# Generated by Django 5.2.9 on 2026-01-05 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_engine', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checklistversion',
            options={'ordering': ['version_number']},
        ),
        migrations.RenameField(
            model_name='checklistversion',
            old_name='version',
            new_name='version_number',
        ),
        migrations.AlterUniqueTogether(
            name='checklistversion',
            unique_together={('template', 'version_number')},
        ),
        migrations.AlterField(
            model_name='checklistversion',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
