# Generated by Django 5.2.9 on 2026-01-05 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_engine', '0002_alter_checklistversion_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checklistversion',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='checklistversion',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='checklistversion',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='checklistversion',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
