# Generated by Django 5.2.9 on 2026-01-06 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_engine', '0003_alter_checklistversion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistitem',
            name='item_type',
            field=models.CharField(choices=[('BOOLEAN', 'Yes / No'), ('TEXT', 'Text'), ('NUMBER', 'Number'), ('PHOTO', 'Photo'), ('DROPDOWN', 'Dropdown')], max_length=20),
        ),
        migrations.CreateModel(
            name='ChecklistItemOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='forms_engine.checklistitem')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
