# Generated by Django 5.2.9 on 2026-01-08 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_engine', '0004_alter_checklistitem_item_type_checklistitemoption'),
        ('org', '0008_delete_departmentsection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checklistversion',
            options={'ordering': ['-version_number']},
        ),
        migrations.AddField(
            model_name='checklisttemplate',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checklist_templates', to='org.department'),
        ),
        migrations.AddField(
            model_name='checklisttemplate',
            name='shops',
            field=models.ManyToManyField(blank=True, help_text='Sections (SMT / ASSY / PACK). Leave empty to apply to all sections.', related_name='checklist_templates', to='org.shop'),
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='item_id',
            field=models.CharField(help_text='Stable identifier (used in rules & integrations)', max_length=100),
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='severity_weight',
            field=models.PositiveSmallIntegerField(default=1, help_text='Severity contribution if non-conforming'),
        ),
        migrations.AlterField(
            model_name='checklisttemplate',
            name='plants',
            field=models.ManyToManyField(blank=True, help_text='Plants where this checklist is applicable', to='org.plant'),
        ),
        migrations.AlterField(
            model_name='checklisttemplate',
            name='products',
            field=models.ManyToManyField(blank=True, help_text='If empty, checklist applies to all products', to='org.product'),
        ),
        migrations.AlterUniqueTogether(
            name='checklistversion',
            unique_together={('template', 'version_number')},
        ),
    ]
