# Generated by Django 5.2.9 on 2026-01-08 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_engine', '0005_alter_checklistversion_options_and_more'),
        ('org', '0008_delete_departmentsection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklisttemplate',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checklist_templates', to='org.department'),
        ),
    ]
