# Generated by Django 5.2.9 on 2026-01-08 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_engine', '0006_alter_checklisttemplate_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklisttemplate',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
