# Generated by Django 5.2.9 on 2026-01-09 13:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_engine', '0007_checklisttemplate_is_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistitem',
            name='severity_weight',
            field=models.PositiveSmallIntegerField(default=0, help_text='Severity contribution if non-conforming'),
        ),
        migrations.AlterField(
            model_name='checklistrule',
            name='condition_value',
            field=models.CharField(help_text='Expected value (YES / NO)', max_length=50),
        ),
        migrations.CreateModel(
            name='ChecklistResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No'), ('NA', 'Not Applicable')], max_length=3)),
                ('remark', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='checklist_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='forms_engine.checklistitem')),
            ],
            options={
                'unique_together': {('item',)},
            },
        ),
    ]
