# Generated by Django 5.2.9 on 2026-01-28 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_engine', '0008_alter_checklistitem_severity_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistitemoption',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_responses', to='forms_engine.checklistitem'),
        ),
    ]
