# Generated by Django 5.2.9 on 2026-01-28 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_engine', '0009_alter_checklistitemoption_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistitemoption',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='forms_engine.checklistitem'),
        ),
    ]
