# Generated by Django 5.2.9 on 2026-01-31 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_engine', '0010_alter_checklistitemoption_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistresponse',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='evidence/'),
        ),
    ]
