# Generated by Django 5.2.9 on 2026-02-02 08:30

import forms_engine.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_engine', '0011_alter_checklistresponse_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistresponse',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=forms_engine.models.evidence_upload_path),
        ),
    ]
