# Generated by Django 5.2.9 on 2026-02-11 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_engine', '0012_alter_checklistresponse_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklisttemplate',
            name='approval_flow',
            field=models.CharField(choices=[('NONE', 'No Approval Required'), ('PD', 'PD Only'), ('PE', 'PE Only'), ('PQE', 'PQE Only'), ('PD_PE', 'PD + PE'), ('PD_PE_PQE', 'PD + PE + PQE (Full Chain)')], default='NONE', help_text='Defines approval requirement for this checklist', max_length=20),
        ),
    ]
