# Generated by Django 5.2.9 on 2026-02-11 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_engine', '0013_checklisttemplate_approval_flow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklisttemplate',
            name='approval_flow',
            field=models.CharField(choices=[('NONE', 'No Approval Required'), ('PD', 'PD Only'), ('PE', 'PE Only'), ('PQE', 'PQE Only'), ('PD_PQE', 'PD + PQE'), ('PE_PQE', 'PE + PQE'), ('PD_PE_PQE', 'PD + PE + PQE (Full Chain)')], default='NONE', help_text='Defines approval requirement for this checklist', max_length=20),
        ),
    ]
