# Generated by Django 5.2.9 on 2026-02-12 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_engine', '0014_alter_checklisttemplate_approval_flow'),
        ('org', '0009_alter_company_options_alter_company_code_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='checklistresponse',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='checklistresponse',
            name='item',
        ),
        migrations.AlterField(
            model_name='checklisttemplate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='checklisttemplate',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='checklisttemplate',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='checklistversion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='checklistversion',
            name='is_active',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='checklistversion',
            name='is_published',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='checklistitem',
            index=models.Index(fields=['section', 'order'], name='forms_engin_section_3b8c85_idx'),
        ),
        migrations.AddIndex(
            model_name='checklistitemoption',
            index=models.Index(fields=['item', 'order'], name='forms_engin_item_id_6d7249_idx'),
        ),
        migrations.AddIndex(
            model_name='checklistsection',
            index=models.Index(fields=['version', 'order'], name='forms_engin_version_fb5553_idx'),
        ),
        migrations.AddIndex(
            model_name='checklisttemplate',
            index=models.Index(fields=['is_active', 'is_archived'], name='forms_engin_is_acti_d19fb5_idx'),
        ),
        migrations.AddIndex(
            model_name='checklisttemplate',
            index=models.Index(fields=['created_at'], name='forms_engin_created_6e6c05_idx'),
        ),
        migrations.AddIndex(
            model_name='checklistversion',
            index=models.Index(fields=['template', 'is_active'], name='forms_engin_templat_5bd3ff_idx'),
        ),
        migrations.AddIndex(
            model_name='checklistversion',
            index=models.Index(fields=['template', 'is_published'], name='forms_engin_templat_cdc96e_idx'),
        ),
        migrations.DeleteModel(
            name='ChecklistResponse',
        ),
    ]
