# Generated by Django 5.2.9 on 2026-02-20 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_engine', '0015_alter_checklistresponse_unique_together_and_more'),
        ('identity', '0013_approvalcategory_remove_role_category_and_more'),
        ('org', '0010_remove_department_org_departm_plant_i_64f986_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklisttemplate',
            name='approval_flow',
        ),
        migrations.AlterField(
            model_name='checklisttemplate',
            name='bitable_app_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='checklisttemplate',
            name='bitable_table_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='checklisttemplate',
            name='plants',
            field=models.ManyToManyField(blank=True, to='org.plant'),
        ),
        migrations.AlterField(
            model_name='checklisttemplate',
            name='products',
            field=models.ManyToManyField(blank=True, to='org.product'),
        ),
        migrations.AlterField(
            model_name='checklisttemplate',
            name='shops',
            field=models.ManyToManyField(blank=True, related_name='checklist_templates', to='org.shop'),
        ),
        migrations.CreateModel(
            name='ChecklistApprovalStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(help_text='Lower number = earlier approval')),
                ('is_required', models.BooleanField(default=True, help_text='If false, approval is optional')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checklist_steps', to='identity.approvalcategory')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_steps', to='forms_engine.checklisttemplate')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('template', 'category')},
            },
        ),
    ]
