# Generated by Django 5.2.9 on 2026-07-25 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_engine', '0016_remove_checklisttemplate_approval_flow_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistitem',
            name='label',
            field=models.TextField(),
        ),
    ]
