# Generated by Django 5.2.14 on 2026-07-27 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_engine', '0017_alter_checklistitem_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklisttemplate',
            name='approval_flow',
            field=models.CharField(choices=[('NONE', 'No Approval Required'), ('PD', 'PD Only'), ('PE', 'PE Only'), ('PQE', 'PQE Only'), ('PD_PQE', 'PD + PQE'), ('PE_PQE', 'PE + PQE'), ('PD_PE_PQE', 'PD + PE + PQE (Full Chain)')], default='NONE', help_text='Defines which roles must approve before submission closes.', max_length=20),
        ),
    ]
