# Generated by Django 5.2.9 on 2026-01-05 09:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forms_engine', '0001_initial'),
        ('org', '0003_product_brand'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('submission_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workflow_state', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('SYNC_PENDING', 'Sync Pending'), ('SYNCED', 'Synced'), ('FAILED', 'Failed'), ('CLOSED', 'Closed')], default='DRAFT', max_length=20)),
                ('severity_score', models.IntegerField(default=0)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='org.line')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='org.plant')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='org.product')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='org.shop')),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='org.station')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to=settings.AUTH_USER_MODEL)),
                ('template_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='forms_engine.checklistversion')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_type', models.CharField(choices=[('BASE', 'Base'), ('RULE', 'Rule')], default='BASE', max_length=10)),
                ('file', models.FileField(upload_to='evidence/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('checklist_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms_engine.checklistitem')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='submissions.submission')),
            ],
        ),
        migrations.CreateModel(
            name='WorkContext',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_color', models.CharField(blank=True, max_length=50)),
                ('shift', models.CharField(choices=[('DAY', 'Day'), ('NIGHT', 'Night')], max_length=10)),
                ('work_date', models.DateField()),
                ('process_type', models.CharField(choices=[('IPQC', 'IPQC'), ('OQC', 'OQC'), ('EHS', 'EHS'), ('MAINTENANCE', 'MAINTENANCE'), ('GENERIC', 'GENERIC')], default='GENERIC', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_work_contexts', to=settings.AUTH_USER_MODEL)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='org.line')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='org.plant')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='org.product')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='org.shop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_work_contexts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='submission',
            name='work_context',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='submissions.workcontext'),
        ),
        migrations.CreateModel(
            name='SubmissionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=100)),
                ('value', models.TextField(blank=True)),
                ('remark', models.TextField(blank=True)),
                ('is_non_conformance', models.BooleanField(default=False)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='submissions.submission')),
            ],
            options={
                'indexes': [models.Index(fields=['submission'], name='submissions_submiss_101d4c_idx'), models.Index(fields=['is_non_conformance'], name='submissions_is_non__29843b_idx')],
            },
        ),
        migrations.CreateModel(
            name='SubmissionSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('cursor', models.PositiveIntegerField(default=0, help_text='How many checklist items have been synced')),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('last_attempt_at', models.DateTimeField(auto_now=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='submissions.submission')),
            ],
            options={
                'unique_together': {('submission', 'target')},
            },
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['workflow_state'], name='submissions_workflo_079c31_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['submitted_at'], name='submissions_submitt_f62c88_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['plant', 'line', 'product'], name='submissions_plant_i_259a91_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['severity_score'], name='submissions_severit_14e806_idx'),
        ),
    ]
