# Generated by Django 5.2.9 on 2026-01-06 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workcontext',
            name='process_type',
            field=models.CharField(choices=[('IPQC', 'IPQC'), ('OQC', 'OQC'), ('FQC', 'FQC'), ('IQC', 'IQC'), ('GENERIC', 'GENERIC')], default='GENERIC', max_length=20),
        ),
    ]
