# Generated by Django 5.2.9 on 2026-01-06 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_alter_workcontext_process_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workcontext',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
