# Generated by Django 5.2.9 on 2026-01-15 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0008_delete_departmentsection'),
        ('submissions', '0004_submissionapproval'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='submissionapproval',
            old_name='approved_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='submissionapproval',
            old_name='approval_status',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='submissionapproval',
            name='model_color',
        ),
        migrations.RemoveField(
            model_name='submissionapproval',
            name='process_type',
        ),
        migrations.RemoveField(
            model_name='submissionapproval',
            name='shift',
        ),
        migrations.RemoveField(
            model_name='submissionapproval',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='submissionapproval',
            name='submitted_by',
        ),
        migrations.RemoveField(
            model_name='submissionapproval',
            name='work_date',
        ),
        migrations.AlterField(
            model_name='submissionapproval',
            name='approved_by',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='submissionapproval',
            name='line',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='org.line'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='submissionapproval',
            name='plant',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='org.plant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='submissionapproval',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='org.product'),
            preserve_default=False,
        ),
    ]
