# Generated by Django 5.2.9 on 2026-01-25 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0005_rename_approved_at_submissionapproval_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='is_synced',
            field=models.BooleanField(default=False),
        ),
    ]
