# Generated by Django 5.2.9 on 2026-01-25 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0006_submission_is_synced'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='is_synced',
        ),
    ]
