# Generated by Django 5.2.9 on 2026-01-28 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_engine', '0009_alter_checklistitemoption_item'),
        ('submissions', '0007_remove_submission_is_synced'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submissionresponse',
            name='item_id',
        ),
        migrations.AddField(
            model_name='submissionresponse',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submission_responses', to='forms_engine.checklistitem'),
        ),
    ]
