# Generated by Django 5.2.9 on 2026-01-28 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0008_remove_submissionresponse_item_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submissionresponse',
            name='item',
        ),
        migrations.AddField(
            model_name='submissionresponse',
            name='item_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
