# Generated by Django 5.2.9 on 2026-01-30 09:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0009_remove_submissionresponse_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='public_approval_token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
