# Generated by Django 5.2.9 on 2026-01-30 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0011_alter_submission_public_approval_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionapproval',
            name='rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
