# Generated by Django 5.2.9 on 2026-02-02 08:36

import django.db.models.deletion
import submissions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0013_alter_submissionapproval_approved_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submissionapproval',
            old_name='pqe_name',
            new_name='approver_name',
        ),
        migrations.RemoveField(
            model_name='submissionapproval',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='submissionapproval',
            name='line',
        ),
        migrations.RemoveField(
            model_name='submissionapproval',
            name='plant',
        ),
        migrations.RemoveField(
            model_name='submissionapproval',
            name='product',
        ),
        migrations.AddField(
            model_name='submissionapproval',
            name='role',
            field=models.CharField(choices=[('PD', 'Product Development'), ('PE', 'Process Engineering'), ('PQE', 'Process Quality Engineering')], default='PQE', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='submissionapproval',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='submissions.submission'),
        ),
        migrations.AlterField(
            model_name='submissionattachment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=submissions.models.evidence_upload_path),
        ),
    ]
