# Generated by Django 5.2.9 on 2026-02-02 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0014_rename_pqe_name_submissionapproval_approver_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='submissionapproval',
            unique_together={('submission', 'role')},
        ),
    ]
