# Generated by Django 5.2.9 on 2026-02-12 18:48

import django.db.models.deletion
import submissions.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_engine', '0015_alter_checklistresponse_unique_together_and_more'),
        ('org', '0009_alter_company_options_alter_company_code_and_more'),
        ('submissions', '0015_alter_submissionapproval_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No'), ('NA', 'Not Applicable')], max_length=3)),
                ('remark', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=submissions.models.evidence_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='submission',
            name='submissions_workflo_079c31_idx',
        ),
        migrations.RemoveIndex(
            model_name='submission',
            name='submissions_submitt_f62c88_idx',
        ),
        migrations.RemoveIndex(
            model_name='submission',
            name='submissions_severit_14e806_idx',
        ),
        migrations.RemoveIndex(
            model_name='submissionresponse',
            name='submissions_submiss_101d4c_idx',
        ),
        migrations.RemoveIndex(
            model_name='submissionresponse',
            name='submissions_is_non__29843b_idx',
        ),
        migrations.AlterField(
            model_name='submission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='plant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='org.plant'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='severity_score',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submitted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='workflow_state',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('SYNC_PENDING', 'Sync Pending'), ('SYNCED', 'Synced'), ('FAILED', 'Failed'), ('CLOSED', 'Closed')], db_index=True, default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='submissionapproval',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='submissionattachment',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='submissionresponse',
            name='is_non_conformance',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='submissionresponse',
            name='item_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='submissionresponse',
            name='remark',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='submissionsynclog',
            name='cursor',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='submissionsynclog',
            name='last_attempt_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='submissionsynclog',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='workcontext',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='workcontext',
            name='is_active',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='workcontext',
            name='plant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='org.plant'),
        ),
        migrations.AlterField(
            model_name='workcontext',
            name='work_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterUniqueTogether(
            name='submissionattachment',
            unique_together={('submission', 'checklist_item', 'attachment_type')},
        ),
        migrations.AlterUniqueTogether(
            name='submissionresponse',
            unique_together={('submission', 'item_id')},
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['workflow_state', 'plant'], name='submissions_workflo_9379c0_idx'),
        ),
        migrations.AddIndex(
            model_name='submissionapproval',
            index=models.Index(fields=['submission', 'role'], name='submissions_submiss_38ff41_idx'),
        ),
        migrations.AddIndex(
            model_name='submissionattachment',
            index=models.Index(fields=['submission'], name='submissions_submiss_7f588b_idx'),
        ),
        migrations.AddIndex(
            model_name='submissionresponse',
            index=models.Index(fields=['submission', 'item_id'], name='submissions_submiss_6c2780_idx'),
        ),
        migrations.AddIndex(
            model_name='submissionresponse',
            index=models.Index(fields=['submission', 'is_non_conformance'], name='submissions_submiss_55ec7d_idx'),
        ),
        migrations.AddIndex(
            model_name='submissionsynclog',
            index=models.Index(fields=['target', 'status'], name='submissions_target_f20d76_idx'),
        ),
        migrations.AddIndex(
            model_name='workcontext',
            index=models.Index(fields=['user', 'is_active'], name='submissions_user_id_8405e9_idx'),
        ),
        migrations.AddIndex(
            model_name='workcontext',
            index=models.Index(fields=['plant', 'work_date'], name='submissions_plant_i_1c150e_idx'),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(condition=models.Q(('workflow_state', 'DRAFT')), fields=('submitted_by', 'template_version', 'work_context'), name='unique_draft_per_user_template_context'),
        ),
        migrations.AddField(
            model_name='checklistresponse',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='forms_engine.checklistitem'),
        ),
        migrations.AddField(
            model_name='checklistresponse',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_responses', to='submissions.submission'),
        ),
        migrations.AddIndex(
            model_name='checklistresponse',
            index=models.Index(fields=['submission', 'item'], name='submissions_submiss_d9059b_idx'),
        ),
        migrations.AddIndex(
            model_name='checklistresponse',
            index=models.Index(fields=['created_at'], name='submissions_created_b1fc66_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='checklistresponse',
            unique_together={('submission', 'item')},
        ),
    ]
