# Generated by Django 5.2.9 on 2026-02-18 03:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_forms', '0002_dynamicformfield_depends_on_field_and_more'),
        ('submissions', '0016_checklistresponse_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicFormSubmission',
            fields=[
                ('submission_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workflow_state', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('SYNC_PENDING', 'Sync Pending'), ('SYNCED', 'Synced'), ('FAILED', 'Failed'), ('CLOSED', 'Closed')], db_index=True, default='DRAFT', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dynamic_form_submissions', to=settings.AUTH_USER_MODEL)),
                ('template_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='dynamic_forms.dynamicformversion')),
                ('work_context', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dynamic_form_submissions', to='submissions.workcontext')),
            ],
        ),
        migrations.CreateModel(
            name='DynamicFormSubmissionValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True)),
                ('remark', models.TextField(blank=True, default='')),
                ('is_non_conformance', models.BooleanField(default=False)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submission_values', to='dynamic_forms.dynamicformfield')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='submissions.dynamicformsubmission')),
            ],
        ),
        migrations.AddConstraint(
            model_name='dynamicformsubmission',
            constraint=models.UniqueConstraint(condition=models.Q(('workflow_state', 'DRAFT')), fields=('submitted_by', 'template_version', 'work_context'), name='unique_dynamic_form_draft'),
        ),
        migrations.AddIndex(
            model_name='dynamicformsubmissionvalue',
            index=models.Index(fields=['submission', 'field'], name='submissions_submiss_404785_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dynamicformsubmissionvalue',
            unique_together={('submission', 'field')},
        ),
    ]
