# Generated by Django 5.2.9 on 2026-02-18 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0017_dynamicformsubmission_dynamicformsubmissionvalue_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicSubmissionSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('last_attempt_at', models.DateTimeField(auto_now=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='submissions.dynamicformsubmission')),
            ],
            options={
                'unique_together': {('submission', 'target')},
            },
        ),
    ]
