# Generated by Django 5.2.9 on 2026-02-18 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0018_dynamicsubmissionsynclog'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicsubmissionsynclog',
            name='http_status',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dynamicsubmissionsynclog',
            name='request_payload',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dynamicsubmissionsynclog',
            name='response_payload',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
