# Generated by Django 5.2.9 on 2026-02-20 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0019_dynamicsubmissionsynclog_http_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='public_approval_token',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
    ]
