# Generated by Django 5.2.9 on 2026-02-20 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0020_alter_submission_public_approval_token'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dynamicformsubmission',
            name='unique_dynamic_form_draft',
        ),
        migrations.AddField(
            model_name='dynamicformsubmission',
            name='public_approval_token',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
    ]
