# Generated by Django 5.2.9 on 2026-02-20 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0021_remove_dynamicformsubmission_unique_dynamic_form_draft_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicSubmissionApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('PD', 'Product Development'), ('PE', 'Process Engineering'), ('PQE', 'Process Quality Engineering')], max_length=10)),
                ('status', models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], max_length=20)),
                ('approver_name', models.CharField(max_length=100)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='submissions.dynamicformsubmission')),
            ],
            options={
                'unique_together': {('submission', 'role')},
            },
        ),
    ]
