# Generated by Django 5.2.9 on 2026-02-20 16:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0023_alter_submission_public_approval_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='public_approval_token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=False),
        ),
    ]
