# Generated by Django 5.2.9 on 2026-02-21 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0013_approvalcategory_remove_role_category_and_more"),
        ("submissions", "0028_cleanup_dynamic_submission_approval"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="submissionapproval",
            name="submissions_submiss_38ff41_idx",
        ),
        migrations.AlterUniqueTogether(
            name="submissionapproval",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="submissionapproval",
            name="approver_role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="identity.role",
            ),
        ),
        migrations.AddField(
            model_name="submissionapproval",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="submission_approvals",
                to="identity.approvalcategory",
            ),
        ),
        migrations.AlterField(
            model_name="dynamicsubmissionapproval",
            name="rejection_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="submissionapproval",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.RemoveField(
            model_name="submissionapproval",
            name="role",
        ),
    ]
