# Generated by Django 5.2.14 on 2026-07-25 10:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_engine', '0017_alter_checklistitem_label'),
        ('submissions', '0029_remove_submissionapproval_submissions_submiss_38ff41_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attachment_type', models.CharField(choices=[('BASE', 'Base'), ('RULE', 'Rule')], default='BASE', max_length=10)),
                ('image', models.BinaryField()),
                ('content_type', models.CharField(default='image/jpeg', max_length=100)),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('checklist_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forms_engine.checklistitem')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='db_images', to='submissions.submission')),
            ],
            options={
                'indexes': [models.Index(fields=['submission'], name='submissions_submiss_764ff3_idx')],
            },
        ),
    ]
