# Generated by Django 5.2.14 on 2026-07-27 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0010_remove_department_org_departm_plant_i_64f986_idx_and_more'),
        ('submissions', '0030_submissionimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='org.line'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='org.product'),
        ),
    ]
