# Generated by Django 5.2.16 on 2026-08-18 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0011_floor_line_floor_section_line_section_and_more'),
        ('submissions', '0031_alter_submission_line_alter_submission_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='floor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='org.floor'),
        ),
        migrations.AddField(
            model_name='submission',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='org.section'),
        ),
        migrations.AddField(
            model_name='workcontext',
            name='floor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='org.floor'),
        ),
        migrations.AddField(
            model_name='workcontext',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='org.section'),
        ),
    ]
