# Generated by Django 5.2.16 on 2026-08-18 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0032_submission_floor_submission_section_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='section',
        ),
        migrations.RemoveField(
            model_name='workcontext',
            name='section',
        ),
    ]
