# Generated by Django 5.2.9 on 2025-12-28 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='position',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
