# Generated by Django 5.2.9 on 2025-12-28 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0002_product_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
