# Generated by Django 5.2.9 on 2026-01-06 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0003_product_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departments', to='org.plant')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('plant', 'code')},
            },
        ),
    ]
