# Generated by Django 5.2.9 on 2026-01-06 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0005_product_company_product_plant_alter_product_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='line',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='plant',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='shop',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='station',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='product',
            name='company',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='org.company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='plant',
            field=models.ForeignKey(blank=True, help_text='Leave empty if product is common across all plants', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='org.plant'),
        ),
    ]
