# Generated by Django 5.2.9 on 2026-01-08 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0006_alter_line_options_alter_plant_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='org.department')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('department', 'code')},
            },
        ),
    ]
