# Generated by Django 5.2.9 on 2026-01-08 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0006_alter_userscope_options_remove_userscope_section_and_more'),
        ('org', '0007_departmentsection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DepartmentSection',
        ),
    ]
