# Generated by Django 5.2.9 on 2026-02-12 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0008_delete_departmentsection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='company',
            name='code',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='plant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='departments', to='org.plant'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='plant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shops', to='org.plant'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['plant'], name='org_departm_plant_i_64f986_idx'),
        ),
        migrations.AddIndex(
            model_name='line',
            index=models.Index(fields=['shop'], name='org_line_shop_id_9e3129_idx'),
        ),
        migrations.AddIndex(
            model_name='plant',
            index=models.Index(fields=['company'], name='org_plant_company_d71fc0_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['company'], name='org_product_company_a71767_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['plant'], name='org_product_plant_i_85e297_idx'),
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['plant'], name='org_shop_plant_i_1e4cb6_idx'),
        ),
        migrations.AddIndex(
            model_name='station',
            index=models.Index(fields=['line'], name='org_station_line_id_56434d_idx'),
        ),
    ]
