# Generated by Django 5.2.9 on 2026-02-12 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0009_alter_company_options_alter_company_code_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='department',
            name='org_departm_plant_i_64f986_idx',
        ),
        migrations.RemoveIndex(
            model_name='line',
            name='org_line_shop_id_9e3129_idx',
        ),
        migrations.RemoveIndex(
            model_name='plant',
            name='org_plant_company_d71fc0_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='org_product_company_a71767_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='org_product_plant_i_85e297_idx',
        ),
        migrations.RemoveIndex(
            model_name='shop',
            name='org_shop_plant_i_1e4cb6_idx',
        ),
        migrations.RemoveIndex(
            model_name='station',
            name='org_station_line_id_56434d_idx',
        ),
        migrations.AddField(
            model_name='company',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='department',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='line',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='station',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
