# Generated by Django 5.2.16 on 2026-08-18 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0010_remove_department_org_departm_plant_i_64f986_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='floors', to='org.plant')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('plant', 'code')},
            },
        ),
        migrations.AddField(
            model_name='line',
            name='floor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lines', to='org.floor'),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='org.plant')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections', to='org.shop')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('plant', 'code')},
            },
        ),
        migrations.AddField(
            model_name='line',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lines', to='org.section'),
        ),
        migrations.CreateModel(
            name='FloorTLAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.CharField(choices=[('ALL', 'All Shifts'), ('DAY', 'Day'), ('NIGHT', 'Night')], default='ALL', max_length=10)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_floor_tl_assignments', to=settings.AUTH_USER_MODEL)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tl_assignments', to='org.floor')),
                ('user', models.ForeignKey(help_text='Team Leader (TL) user', on_delete=django.db.models.deletion.CASCADE, related_name='floor_tl_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['floor', '-created_at'],
                'indexes': [models.Index(fields=['floor', 'is_active'], name='org_floortl_floor_i_bba082_idx'), models.Index(fields=['user', 'is_active'], name='org_floortl_user_id_747f1f_idx')],
            },
        ),
        migrations.CreateModel(
            name='IPQCMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.CharField(choices=[('ALL', 'All Shifts'), ('DAY', 'Day'), ('NIGHT', 'Night')], default='ALL', max_length=10)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ipqc_mappings', to=settings.AUTH_USER_MODEL)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ipqc_mappings', to='org.floor')),
                ('lines', models.ManyToManyField(blank=True, help_text='Assigned lines for this IPQC (leave empty for all lines in section/floor)', related_name='ipqc_mappings', to='org.line')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ipqc_mappings', to='org.plant')),
                ('user', models.ForeignKey(help_text='IPQC Inspector / Operator', on_delete=django.db.models.deletion.CASCADE, related_name='ipqc_mappings', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ipqc_mappings', to='org.section')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='org_ipqcmap_user_id_bd7a8e_idx'), models.Index(fields=['plant', 'floor', 'section'], name='org_ipqcmap_plant_i_8ab8bd_idx')],
            },
        ),
        migrations.CreateModel(
            name='SectionPQEAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_section_pqe_assignments', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pqe_assignments', to='org.section')),
                ('user', models.ForeignKey(help_text='Product Quality Engineer (PQE) user', on_delete=django.db.models.deletion.CASCADE, related_name='section_pqe_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['section', '-created_at'],
                'indexes': [models.Index(fields=['section', 'is_active'], name='org_section_section_5a64c6_idx'), models.Index(fields=['user', 'is_active'], name='org_section_user_id_97694e_idx')],
            },
        ),
    ]
