# Generated by Django 5.2.16 on 2026-08-18 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0011_floor_line_floor_section_line_section_and_more'),
        ('submissions', '0033_remove_submission_section_remove_workcontext_section'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopPQEAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['shop', '-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='section',
            name='plant',
        ),
        migrations.RemoveField(
            model_name='section',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='ipqcmapping',
            name='section',
        ),
        migrations.RemoveField(
            model_name='sectionpqeassignment',
            name='section',
        ),
        migrations.RemoveField(
            model_name='line',
            name='section',
        ),
        migrations.RemoveField(
            model_name='sectionpqeassignment',
            name='assigned_by',
        ),
        migrations.RemoveField(
            model_name='sectionpqeassignment',
            name='user',
        ),
        migrations.RemoveIndex(
            model_name='ipqcmapping',
            name='org_ipqcmap_plant_i_8ab8bd_idx',
        ),
        migrations.AddField(
            model_name='ipqcmapping',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ipqc_mappings', to='org.shop'),
        ),
        migrations.AlterField(
            model_name='ipqcmapping',
            name='lines',
            field=models.ManyToManyField(blank=True, help_text='Assigned lines for this IPQC (leave empty for all lines in shop/floor)', related_name='ipqc_mappings', to='org.line'),
        ),
        migrations.AddIndex(
            model_name='ipqcmapping',
            index=models.Index(fields=['plant', 'floor', 'shop'], name='org_ipqcmap_plant_i_3e2e8e_idx'),
        ),
        migrations.AddField(
            model_name='shoppqeassignment',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_shop_pqe_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shoppqeassignment',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pqe_assignments', to='org.shop'),
        ),
        migrations.AddField(
            model_name='shoppqeassignment',
            name='user',
            field=models.ForeignKey(help_text='Product Quality Engineer (PQE) user', on_delete=django.db.models.deletion.CASCADE, related_name='shop_pqe_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Section',
        ),
        migrations.DeleteModel(
            name='SectionPQEAssignment',
        ),
        migrations.AddIndex(
            model_name='shoppqeassignment',
            index=models.Index(fields=['shop', 'is_active'], name='org_shoppqe_shop_id_ecb402_idx'),
        ),
        migrations.AddIndex(
            model_name='shoppqeassignment',
            index=models.Index(fields=['user', 'is_active'], name='org_shoppqe_user_id_f51a67_idx'),
        ),
    ]
