# Generated by Django 5.2.9 on 2026-01-05 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forms_engine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='IntegrationTemplateMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_table_id', models.CharField(max_length=100)),
                ('enabled', models.BooleanField(default=True)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_mappings', to='integrations.integrationtarget')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_mappings', to='forms_engine.checklisttemplate')),
            ],
            options={
                'unique_together': {('template', 'target')},
            },
        ),
        migrations.CreateModel(
            name='IntegrationFieldMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=100)),
                ('external_field', models.CharField(max_length=100)),
                ('transform', models.CharField(blank=True, max_length=50)),
                ('template_mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='integrations.integrationtemplatemapping')),
            ],
        ),
    ]
