# Generated by Django 5.2.9 on 2026-02-12 18:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_engine', '0015_alter_checklistresponse_unique_together_and_more'),
        ('integrations', '0001_initial'),
        ('org', '0009_alter_company_options_alter_company_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='integrationtarget',
            options={'ordering': ['name']},
        ),
        migrations.AlterUniqueTogether(
            name='integrationtemplatemapping',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='integrationtarget',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='integrationtemplatemapping',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='integrationtemplatemapping',
            name='plant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='integration_mappings', to='org.plant'),
        ),
        migrations.AlterField(
            model_name='integrationfieldmapping',
            name='transform',
            field=models.CharField(blank=True, help_text='Optional transformation logic key', max_length=50),
        ),
        migrations.AlterField(
            model_name='integrationtarget',
            name='code',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='integrationtarget',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='integrationtemplatemapping',
            name='enabled',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterUniqueTogether(
            name='integrationfieldmapping',
            unique_together={('template_mapping', 'item_id')},
        ),
        migrations.AlterUniqueTogether(
            name='integrationtemplatemapping',
            unique_together={('plant', 'template', 'target')},
        ),
        migrations.AddIndex(
            model_name='integrationfieldmapping',
            index=models.Index(fields=['template_mapping'], name='integration_templat_a3d5d4_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationtemplatemapping',
            index=models.Index(fields=['plant', 'enabled'], name='integration_plant_i_d9a910_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationtemplatemapping',
            index=models.Index(fields=['template', 'enabled'], name='integration_templat_3b3426_idx'),
        ),
    ]
