# Generated by Django 5.2.9 on 2026-08-27 07:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org', '0012_shoppqeassignment_alter_section_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QRScanSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code_1', models.CharField(help_text='First QR code scanned', max_length=1000)),
                ('qr_code_2', models.CharField(help_text='Second QR code scanned', max_length=1000)),
                ('is_match', models.BooleanField(db_index=True, help_text='True if both QR codes matched (PASS), False otherwise (FAIL)')),
                ('result', models.CharField(choices=[('PASS', 'Pass'), ('FAIL', 'Fail')], db_index=True, max_length=10)),
                ('scanned_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, default='')),
                ('plant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_scan_sessions', to='org.plant')),
                ('scanned_by', models.ForeignKey(blank=True, help_text='User who performed the scan', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_scan_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'QR Scan Session',
                'verbose_name_plural': 'QR Scan Sessions',
                'ordering': ['-scanned_at'],
                'indexes': [models.Index(fields=['-scanned_at'], name='qr_scanner__scanned_96e015_idx'), models.Index(fields=['result', '-scanned_at'], name='qr_scanner__result_66a2b5_idx'), models.Index(fields=['scanned_by', '-scanned_at'], name='qr_scanner__scanned_ac44ee_idx')],
            },
        ),
    ]
