# Generated by Django 5.2.9 on 2026-01-05 09:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('submissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CAPA',
            fields=[
                ('capa_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('severity', models.IntegerField()),
                ('rca_summary', models.TextField(blank=True)),
                ('status', models.CharField(default='OPEN', max_length=30)),
                ('due_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_capas', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capas', to='submissions.submission')),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='capa_capa_status_04b7b0_idx'), models.Index(fields=['severity'], name='capa_capa_severit_dbf64b_idx'), models.Index(fields=['created_at'], name='capa_capa_created_617ceb_idx')],
            },
        ),
    ]
