# Generated by Django 5.2.9 on 2026-01-27 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capa', '0001_initial'),
        ('identity', '0006_alter_userscope_options_remove_userscope_section_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capa',
            name='owner',
        ),
        migrations.AddField(
            model_name='capa',
            name='assigned_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='capas', to='identity.role'),
        ),
    ]
