# Generated by Django 5.2.9 on 2026-01-27 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capa', '0002_remove_capa_owner_capa_assigned_role'),
        ('identity', '0006_alter_userscope_options_remove_userscope_section_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='capa',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_capas_by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='capa',
            name='assigned_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_capas', to='identity.role'),
        ),
    ]
