# Generated by Django 5.2.9 on 2026-01-27 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capa', '0003_capa_assigned_by_alter_capa_assigned_role'),
        ('identity', '0006_alter_userscope_options_remove_userscope_section_and_more'),
        ('submissions', '0007_remove_submission_is_synced'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='capa',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='capa',
            name='assigned_role',
        ),
        migrations.AddField(
            model_name='capa',
            name='capa_plan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='capa',
            name='capa_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='capa_action_capas', to='identity.role'),
        ),
        migrations.AddField(
            model_name='capa',
            name='rca_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rca_capas', to='identity.role'),
        ),
        migrations.AddField(
            model_name='capa',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='capa',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_capas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='capa',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='capa',
            name='rca_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='capa',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('ASSIGNED', 'Assigned'), ('ACTION_DONE', 'Action Done'), ('REJECTED', 'Rejected'), ('CLOSED', 'Closed')], default='OPEN', max_length=20),
        ),
        migrations.AddIndex(
            model_name='capa',
            index=models.Index(fields=['due_date'], name='capa_capa_due_dat_2ead0d_idx'),
        ),
    ]
