# Generated by Django 5.2.9 on 2026-02-12 21:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approval',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='approval',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='approval',
            name='object_id',
            field=models.CharField(db_index=True, help_text='Primary key of the approved object', max_length=100),
        ),
        migrations.AlterField(
            model_name='approval',
            name='object_type',
            field=models.CharField(db_index=True, help_text='Model name of the approved object (e.g., Submission)', max_length=50),
        ),
        migrations.AlterField(
            model_name='approval',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AddIndex(
            model_name='approval',
            index=models.Index(fields=['object_type', 'object_id'], name='workflow_ap_object__9911f9_idx'),
        ),
        migrations.AddIndex(
            model_name='approval',
            index=models.Index(fields=['status', 'created_at'], name='workflow_ap_status_153401_idx'),
        ),
    ]
