# Generated by Django 5.2.9 on 2026-02-17 23:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0010_permission_rolepermission'),
        ('org', '0010_remove_department_org_departm_plant_i_64f986_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicFormTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submission_mode', models.CharField(choices=[('AGGREGATED', 'One row per submission'), ('FULL', 'One row per field')], db_index=True, default='AGGREGATED', max_length=20)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('source_bitable_app_token', models.CharField(max_length=255)),
                ('source_bitable_table_id', models.CharField(max_length=255)),
                ('submission_bitable_app_token', models.CharField(max_length=255)),
                ('submission_bitable_table_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dynamic_form_templates', to='org.department')),
                ('plants', models.ManyToManyField(blank=True, to='org.plant')),
                ('products', models.ManyToManyField(blank=True, to='org.product')),
                ('shops', models.ManyToManyField(blank=True, to='org.shop')),
            ],
        ),
        migrations.CreateModel(
            name='DynamicFormVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='dynamic_forms.dynamicformtemplate')),
            ],
            options={
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='DynamicFormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('help_text', models.CharField(blank=True, max_length=255)),
                ('field_kind', models.CharField(choices=[('INPUT', 'Input Field'), ('SUPPORT', 'Supporting / Reference Data')], max_length=20)),
                ('data_type', models.CharField(choices=[('TEXT', 'Text'), ('NUMBER', 'Number'), ('DROPDOWN', 'Dropdown'), ('BOOLEAN', 'Yes / No'), ('IMAGE', 'Image')], max_length=20)),
                ('required', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('bitable_column_id', models.CharField(blank=True, help_text='Optional source column for data / reference', max_length=255, null=True)),
                ('dropdown_config', models.JSONField(blank=True, default=dict, help_text='\n        {\n          source: "manual" | "auto",\n          options: ["OK","NG"],\n          depends_on: <field_id>,\n          reference_column: <bitable_column_id>\n        }\n        ')),
                ('number_config', models.JSONField(blank=True, default=dict, help_text='\n        {\n          min: { type: "static"|"column", value: 220|"col_id" },\n          max: { type: "static"|"column", value: 240|"col_id" }\n        }\n        ')),
                ('dependency_config', models.JSONField(blank=True, default=dict, help_text='\n        {\n          parent_field: <field_id>,\n          operator: "EQ"|"IN",\n          value: "NG"\n        }\n        ')),
                ('reference_config', models.JSONField(blank=True, default=dict, help_text='\n        {\n          enabled: true,\n          source_column: <bitable_column_id>\n        }\n        ')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='dynamic_forms.dynamicformversion')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='DynamicTemplateRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requires_work_context', models.BooleanField(default=False, help_text='If enabled, user must have an active Work Context to submit this template')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dynamic_template_assignments', to='identity.role')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='dynamic_forms.dynamicformtemplate')),
            ],
        ),
        migrations.AddIndex(
            model_name='dynamicformtemplate',
            index=models.Index(fields=['is_active', 'is_archived'], name='dynamic_for_is_acti_226d30_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dynamicformversion',
            unique_together={('template', 'version_number')},
        ),
        migrations.AddIndex(
            model_name='dynamicformfield',
            index=models.Index(fields=['version'], name='dynamic_for_version_06211a_idx'),
        ),
        migrations.AddIndex(
            model_name='dynamicformfield',
            index=models.Index(fields=['data_type'], name='dynamic_for_data_ty_3f6fa2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dynamictemplaterole',
            unique_together={('template', 'role')},
        ),
    ]
