# Generated by Django 5.2.9 on 2026-02-18 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicformfield',
            name='depends_on_field',
            field=models.ForeignKey(blank=True, help_text='Another dropdown field this field depends on', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent_fields', to='dynamic_forms.dynamicformfield'),
        ),
        migrations.AlterField(
            model_name='dynamicformfield',
            name='bitable_column_id',
            field=models.CharField(blank=True, help_text='Bitable column used to populate this field', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dynamicformfield',
            name='dependency_config',
            field=models.JSONField(blank=True, default=dict, help_text='\n        {\n          "operator": "EQ" | "IN",\n          "parent_column": "<bitable_column_id>",\n          "self_column": "<bitable_column_id>"\n        }\n        '),
        ),
        migrations.AlterField(
            model_name='dynamicformfield',
            name='dropdown_config',
            field=models.JSONField(blank=True, default=dict, help_text='\n        {\n          "source": "bitable" | "manual",\n          "label_column": "<bitable_column_id>",\n          "value_column": "<bitable_column_id>",\n          "options": ["OK", "NG"]   // only if source = manual\n        }\n        '),
        ),
        migrations.AlterField(
            model_name='dynamicformfield',
            name='number_config',
            field=models.JSONField(blank=True, default=dict, help_text='\n        {\n          "min": { "type": "static" | "column", "value": 220 | "<col_id>" },\n          "max": { "type": "static" | "column", "value": 240 | "<col_id>" }\n        }\n        '),
        ),
        migrations.AlterField(
            model_name='dynamicformfield',
            name='reference_config',
            field=models.JSONField(blank=True, default=dict, help_text='\n        {\n          "enabled": true,\n          "source": "field" | "bitable"\n        }\n        '),
        ),
    ]
