# Generated by Django 5.2.9 on 2026-02-18 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_forms', '0002_dynamicformfield_depends_on_field_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicFormStandardRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_source', models.CharField(choices=[('MANUAL', 'Manual Value'), ('BITABLE', 'Bitable Column')], max_length=20)),
                ('manual_value', models.CharField(blank=True, max_length=255, null=True)),
                ('bitable_column_id', models.CharField(blank=True, max_length=255, null=True)),
                ('operator', models.CharField(choices=[('EQ', 'Equal'), ('LTE', 'Less Than or Equal'), ('GTE', 'Greater Than or Equal')], max_length=10)),
                ('dependency_filters', models.JSONField(blank=True, default=list, help_text='\n        [\n          {\n            "field_id": "<DynamicFormField.id>",\n            "bitable_column": "<column_id>"\n          }\n        ]\n        ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standard_rules', to='dynamic_forms.dynamicformfield')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standard_rules', to='dynamic_forms.dynamicformversion')),
            ],
            options={
                'indexes': [models.Index(fields=['version'], name='dynamic_for_version_d7105c_idx'), models.Index(fields=['target_field'], name='dynamic_for_target__8576ed_idx')],
            },
        ),
    ]
