# Generated by Django 5.2.9 on 2026-02-20 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_forms', '0003_dynamicformstandardrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicformtemplate',
            name='approval_flow',
            field=models.CharField(choices=[('NONE', 'No Approval Required'), ('PD', 'PD Only'), ('PE', 'PE Only'), ('PQE', 'PQE Only'), ('PD_PQE', 'PD + PQE'), ('PE_PQE', 'PE + PQE'), ('PD_PE_PQE', 'PD + PE + PQE (Full Chain)')], default='NONE', help_text='Defines approval requirement for this checklist', max_length=20),
        ),
    ]
