# Generated by Django 5.2.9 on 2026-02-20 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_forms', '0004_dynamicformtemplate_approval_flow'),
        ('identity', '0013_approvalcategory_remove_role_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dynamicformtemplate',
            name='approval_flow',
        ),
        migrations.CreateModel(
            name='TemplateApprovalStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(help_text='Approval order for this template')),
                ('is_required', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identity.approvalcategory')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_steps', to='dynamic_forms.dynamicformtemplate')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('template', 'category')},
            },
        ),
    ]
