# Generated by Django 5.2.14 on 2026-07-25 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_forms', '0005_remove_dynamicformtemplate_approval_flow_and_more'),
        ('notifications', '0002_bitableconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicformtemplate',
            name='alert_enabled',
            field=models.BooleanField(default=False, help_text='Enable alert if not filled on schedule'),
        ),
        migrations.AddField(
            model_name='dynamicformtemplate',
            name='lark_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='notifications.larkconfig'),
        ),
        migrations.AddField(
            model_name='dynamicformtemplate',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, help_text='Scheduled time for the template to be filled', null=True),
        ),
    ]
