# Generated by Django 5.2.14 on 2026-07-25 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BitableConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Friendly identifier for the Bitable configuration', max_length=100, unique=True)),
                ('app_token', models.CharField(help_text='Bitable App Token', max_length=255)),
                ('table_id', models.CharField(help_text='Bitable Table ID', max_length=255)),
            ],
            options={
                'verbose_name': 'Bitable Configuration',
                'verbose_name_plural': 'Bitable Configurations',
            },
        ),
    ]
