# Generated by Django 5.2.9 on 2026-02-05 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forms_engine', '0012_alter_checklistresponse_photo'),
        ('org', '0008_delete_departmentsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulerControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_run', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FormSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_type', models.CharField(choices=[('interval', 'Interval Based'), ('shift_limit', 'Times Per Shift'), ('daily', 'Daily')], max_length=20)),
                ('interval_minutes', models.IntegerField(blank=True, null=True)),
                ('times_per_shift', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='org.line')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='org.plant')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='forms_engine.checklisttemplate')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_at', models.DateTimeField()),
                ('is_completed', models.BooleanField(default=False)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='scheduler.formschedule')),
            ],
        ),
    ]
