# Generated by Django 5.2.9 on 2026-02-05 10:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_engine', '0012_alter_checklistresponse_photo'),
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formschedule',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='scheduledinstance',
            options={'ordering': ['-expected_at']},
        ),
        migrations.AlterModelOptions(
            name='schedulercontrol',
            options={'verbose_name': 'Scheduler Control', 'verbose_name_plural': 'Scheduler Control'},
        ),
        migrations.RemoveField(
            model_name='formschedule',
            name='line',
        ),
        migrations.RemoveField(
            model_name='formschedule',
            name='plant',
        ),
        migrations.AddField(
            model_name='formschedule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formschedule',
            name='daily_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduledinstance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scheduledinstance',
            name='created_submission_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formschedule',
            name='interval_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formschedule',
            name='template',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='forms_engine.checklisttemplate'),
        ),
        migrations.AlterField(
            model_name='formschedule',
            name='times_per_shift',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='scheduledinstance',
            index=models.Index(fields=['expected_at'], name='scheduler_s_expecte_eb1e54_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledinstance',
            index=models.Index(fields=['is_completed'], name='scheduler_s_is_comp_0fac7e_idx'),
        ),
    ]
