# Generated by Django 5.2.9 on 2026-02-05 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_alter_formschedule_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledinstance',
            name='created_submission_id',
        ),
        migrations.AddField(
            model_name='scheduledinstance',
            name='created_submission_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
