# Generated by Django 5.2.14 on 2026-07-27 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_missedformalert'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='missedformalert',
            new_name='scheduler_m_user_id_ecb471_idx',
            old_name='scheduler_m_user_id_123456_idx',
        ),
        migrations.RenameIndex(
            model_name='missedformalert',
            new_name='scheduler_m_created_2ebc03_idx',
            old_name='scheduler_m_created_123456_idx',
        ),
    ]
