# Generated by Django 5.2.16 on 2026-07-28 06:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_engine', '0018_checklisttemplate_approval_flow'),
        ('scheduler', '0005_rename_scheduler_m_user_id_123456_idx_scheduler_m_user_id_ecb471_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='missedformalert',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='missedformalert',
            name='business_date',
            field=models.DateField(blank=True, db_index=True, help_text='Business date (work_date) for deduplication', null=True),
        ),
        migrations.AddField(
            model_name='missedformalert',
            name='shift',
            field=models.CharField(blank=True, db_index=True, help_text='Shift (DAY/NIGHT) for deduplication', max_length=10, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='missedformalert',
            unique_together={('template', 'user', 'business_date', 'shift')},
        ),
        migrations.AddIndex(
            model_name='missedformalert',
            index=models.Index(fields=['template', 'user', 'business_date', 'shift'], name='idx_alert_dedup'),
        ),
    ]
